import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Palette ──────────────────────────────────────────────────────────────────
const C = {
  bg:          [10,  11,  16]  as [number, number, number],
  card:        [18,  19,  26]  as [number, number, number],
  border:      [30,  32,  48]  as [number, number, number],
  primary:     [0,   212, 255] as [number, number, number],
  emerald:     [0,   230, 118] as [number, number, number],
  crimson:     [255, 59,  92]  as [number, number, number],
  amber:       [255, 184, 0]   as [number, number, number],
  purple:      [180, 79,  255] as [number, number, number],
  white:       [255, 255, 255] as [number, number, number],
  light:       [200, 205, 220] as [number, number, number],
  muted:       [110, 115, 140] as [number, number, number],
};

const RISK_LABEL_COLORS: Record<string, [number, number, number]> = {
  CRITICAL: C.crimson,
  HIGH:     C.amber,
  MEDIUM:   [255, 109, 0],
  LOW:      C.primary,
};

const RISK_TYPE_COLORS: Record<string, [number, number, number]> = {
  self_approval:              C.crimson,
  invoice_splitting:          C.amber,
  rapid_payment:              [255, 109, 0],
  large_payment_no_senior:    C.amber,
  missing_approval:           C.crimson,
  duplicate_invoice:          [255, 109, 0],
  amount_mismatch:            C.purple,
  dormant_vendor:             [0, 188, 212],
};

function labelColor(label: string): [number, number, number] {
  return RISK_LABEL_COLORS[label] ?? C.muted;
}

function setFill(doc: jsPDF, rgb: [number, number, number]) {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}
function setDraw(doc: jsPDF, rgb: [number, number, number]) {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}
function setTxt(doc: jsPDF, rgb: [number, number, number]) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

// ─── Header / Footer ──────────────────────────────────────────────────────────
function addPageHeader(doc: jsPDF, pageNum: number, totalPages: number) {
  const W = doc.internal.pageSize.getWidth();

  // Top bar
  setFill(doc, C.card);
  doc.rect(0, 0, W, 14, "F");
  setDraw(doc, C.primary);
  doc.setLineWidth(0.4);
  doc.line(0, 14, W, 14);

  // Brand
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  setTxt(doc, C.primary);
  doc.text("FinSentry", 10, 9);
  doc.setFont("helvetica", "normal");
  setTxt(doc, C.muted);
  doc.text("Financial Risk Detection & Compliance Platform", 30, 9);

  // Page n / N
  setTxt(doc, C.muted);
  doc.setFontSize(8);
  doc.text(`Page ${pageNum} of ${totalPages}`, W - 10, 9, { align: "right" });
}

function addPageFooter(doc: jsPDF) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  setDraw(doc, C.border);
  doc.setLineWidth(0.3);
  doc.line(10, H - 10, W - 10, H - 10);
  doc.setFontSize(7);
  setTxt(doc, C.muted);
  doc.text("CONFIDENTIAL — For internal audit use only. Generated by FinSentry Autonomous Audit System.", W / 2, H - 5, { align: "center" });
}

// ─── Cover Page ───────────────────────────────────────────────────────────────
function addCoverPage(doc: jsPDF, invData: any) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  // Dark background
  setFill(doc, C.bg);
  doc.rect(0, 0, W, H, "F");

  // Top accent bar
  setFill(doc, C.primary);
  doc.rect(0, 0, W, 2, "F");

  // Logo area
  setFill(doc, C.card);
  doc.rect(0, 20, W, 60, "F");

  // FinSentry
  doc.setFont("helvetica", "bold");
  doc.setFontSize(36);
  setTxt(doc, C.primary);
  doc.text("FinSentry", W / 2, 52, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  setTxt(doc, C.light);
  doc.text("Financial Risk Detection & Compliance Platform", W / 2, 62, { align: "center" });

  // Horizontal rule
  setDraw(doc, C.border);
  doc.setLineWidth(0.5);
  doc.line(20, 70, W - 20, 70);

  // Report title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  setTxt(doc, C.white);
  doc.text("AUTONOMOUS AUDIT INVESTIGATION REPORT", W / 2, 92, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  setTxt(doc, C.muted);
  const runAt = invData?.audit_session?.run_at
    ? new Date(invData.audit_session.run_at).toLocaleString(undefined, {
        year: "numeric", month: "long", day: "numeric",
        hour: "2-digit", minute: "2-digit",
      })
    : new Date().toLocaleString();
  doc.text(`Generated: ${runAt}`, W / 2, 102, { align: "center" });

  // Stats panel
  const session = invData?.audit_session ?? {};
  const records = session.records_analyzed ?? {};
  const statsY = 125;
  const cols = 4;
  const statW = (W - 40) / cols;

  const stats = [
    { label: "Risk Findings", value: String(invData?.total_risks ?? 0), color: C.crimson },
    { label: "Vendors Analyzed", value: String(records.vendors ?? 0), color: C.primary },
    { label: "Invoices Reviewed", value: String(records.invoices ?? 0), color: C.amber },
    { label: "Transactions Checked", value: String(records.transactions ?? 0), color: C.emerald },
  ];

  stats.forEach((s, i) => {
    const x = 20 + i * statW;
    setFill(doc, C.card);
    doc.rect(x, statsY, statW - 4, 28, "F");
    setDraw(doc, s.color);
    doc.setLineWidth(0.6);
    doc.rect(x, statsY, statW - 4, 28, "S");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    setTxt(doc, s.color);
    doc.text(s.value, x + (statW - 4) / 2, statsY + 13, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    setTxt(doc, C.muted);
    doc.text(s.label.toUpperCase(), x + (statW - 4) / 2, statsY + 23, { align: "center" });
  });

  // Classification banner
  setFill(doc, [40, 10, 10]);
  doc.rect(20, H - 50, W - 40, 12, "F");
  setDraw(doc, C.crimson);
  doc.setLineWidth(0.4);
  doc.rect(20, H - 50, W - 40, 12, "S");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  setTxt(doc, C.crimson);
  doc.text("⚠  CONFIDENTIAL — INTERNAL AUDIT USE ONLY", W / 2, H - 41, { align: "center" });

  // Deloitte / Hackathon tag
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setTxt(doc, C.muted);
  doc.text("Deloitte Hackplosion 2026  ·  Team YOLO  ·  SRM Institute of Science & Technology", W / 2, H - 28, { align: "center" });
}

// ─── Section heading ──────────────────────────────────────────────────────────
function sectionHeading(doc: jsPDF, y: number, title: string): number {
  const W = doc.internal.pageSize.getWidth();
  setFill(doc, C.card);
  doc.rect(10, y, W - 20, 10, "F");
  setDraw(doc, C.primary);
  doc.setLineWidth(0.5);
  doc.line(10, y + 10, W - 10, y + 10);

  setFill(doc, C.primary);
  doc.rect(10, y, 2.5, 10, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  setTxt(doc, C.primary);
  doc.text(title, 16, y + 7);

  return y + 16;
}

// ─── Case Explainability PDF (single beautiful page) ─────────────────────────
export function generateCasePDF(explainData: any) {
  const doc = new jsPDF({ unit: "mm", format: "a4", compress: true });
  const W = 210;

  // Full dark background
  setFill(doc, C.bg);
  doc.rect(0, 0, W, 297, "F");

  // ── TOP HEADER BAR ──────────────────────────────────────────────────────────
  setFill(doc, C.card);
  doc.rect(0, 0, W, 14, "F");
  setFill(doc, C.primary);
  doc.rect(0, 14, W, 0.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  setTxt(doc, C.primary);
  doc.text("FinSentry", 10, 9);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setTxt(doc, C.muted);
  doc.text("Autonomous Case Investigation Report  ·  CONFIDENTIAL", 28, 9);
  setTxt(doc, C.muted);
  doc.text(new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" }), W - 10, 9, { align: "right" });

  // ── CASE HERO ───────────────────────────────────────────────────────────────
  const riskLabel  = explainData.risk_label ?? "UNKNOWN";
  const riskColor  = RISK_LABEL_COLORS[riskLabel] ?? C.muted;
  const riskScore  = explainData.risk_score != null ? Math.round(explainData.risk_score * 100) : null;
  const riskType   = (explainData.risk_type ?? "").replace(/_/g, " ").toUpperCase();

  setFill(doc, C.card);
  doc.rect(0, 14.5, W, 30, "F");
  setFill(doc, riskColor);
  doc.rect(0, 14.5, 3.5, 30, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  setTxt(doc, C.muted);
  doc.text(explainData.case_id ?? "—", 8, 21);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  setTxt(doc, C.white);
  doc.text(explainData.vendor ?? "Unknown Vendor", 8, 30);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  setTxt(doc, C.muted);
  doc.text(riskType, 8, 37.5);

  // Risk label badge
  const badgeX = W - 58;
  setFill(doc, riskColor);
  doc.roundedRect(badgeX, 17.5, 28, 8, 1.5, 1.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  setTxt(doc, C.white);
  doc.text(riskLabel, badgeX + 14, 23, { align: "center" });

  // Risk score
  if (riskScore !== null) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    setTxt(doc, riskColor);
    doc.text(`${riskScore}%`, W - 16, 30, { align: "right" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6);
    setTxt(doc, C.muted);
    doc.text("RISK SCORE", W - 10, 36.5, { align: "right" });
  }

  // Divider below hero
  setDraw(doc, C.border);
  doc.setLineWidth(0.3);
  doc.line(0, 44.5, W, 44.5);

  // ── 2-COLUMN CONTENT ────────────────────────────────────────────────────────
  const COL1_X = 10;
  const COL2_X = 112;
  const COL_W  = 96;
  let   y1     = 51;
  let   y2     = 51;

  // ── LEFT COLUMN ─────────────────────────────────────────────────────────────

  // A) WHY FLAGGED
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  setTxt(doc, C.crimson);
  doc.text("WHY FLAGGED", COL1_X, y1);
  setDraw(doc, C.crimson);
  doc.setLineWidth(0.3);
  doc.line(COL1_X, y1 + 1, COL1_X + COL_W, y1 + 1);
  y1 += 5;

  const why      = explainData.why_flagged ?? {};
  const ruleDesc = why.rule_description ?? "No description available.";
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  setTxt(doc, C.light);
  const ruleLines = doc.splitTextToSize(ruleDesc, COL_W - 2);
  doc.text(ruleLines, COL1_X, y1);
  y1 += ruleLines.length * 4.6 + 3;

  // Policy violation callout box
  if (why.summary) {
    const sumLines = doc.splitTextToSize(why.summary, COL_W - 10);
    const boxH     = sumLines.length * 4.6 + 7;
    setFill(doc, [35, 10, 14]);
    setDraw(doc, [90, 25, 38]);
    doc.setLineWidth(0.3);
    doc.roundedRect(COL1_X, y1, COL_W, boxH, 1.5, 1.5, "FD");
    setFill(doc, C.crimson);
    doc.rect(COL1_X, y1, 2.5, boxH, "F");
    doc.setFont("helvetica", "italic");
    doc.setFontSize(7.8);
    setTxt(doc, [225, 155, 165]);
    doc.text(sumLines, COL1_X + 6, y1 + 5);
    y1 += boxH + 5;
  }

  // B) ACTORS INVOLVED
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  setTxt(doc, C.primary);
  doc.text("ACTORS INVOLVED", COL1_X, y1);
  setDraw(doc, C.primary);
  doc.setLineWidth(0.3);
  doc.line(COL1_X, y1 + 1, COL1_X + COL_W, y1 + 1);
  y1 += 5;

  const actors = why.actors_involved ?? [];
  if (actors.length > 0) {
    let ax = COL1_X;
    actors.forEach((actor: string) => {
      const aW = doc.getTextWidth(actor) + 7;
      setFill(doc, [18, 24, 48]);
      setDraw(doc, C.primary);
      doc.setLineWidth(0.3);
      doc.roundedRect(ax, y1 - 3.5, aW, 7, 1.5, 1.5, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7.5);
      setTxt(doc, C.primary);
      doc.text(actor, ax + 3.5, y1 + 0.5);
      ax += aW + 3;
    });
    y1 += 9;
  } else {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    setTxt(doc, C.muted);
    doc.text("No actors identified.", COL1_X, y1);
    y1 += 7;
  }

  // C) EVIDENCE
  y1 += 2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  setTxt(doc, C.primary);
  doc.text("EVIDENCE", COL1_X, y1);
  setDraw(doc, C.primary);
  doc.setLineWidth(0.3);
  doc.line(COL1_X, y1 + 1, COL1_X + COL_W, y1 + 1);
  y1 += 5;

  const evidence = why.evidence ?? [];
  evidence.forEach((ev: string) => {
    const evLines = doc.splitTextToSize(ev, COL_W - 10);
    const evH     = evLines.length * 4.4 + 5;
    setFill(doc, C.card);
    doc.rect(COL1_X, y1 - 1.5, COL_W, evH, "F");
    setFill(doc, C.primary);
    doc.circle(COL1_X + 2.8, y1 + 1.5, 1, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.8);
    setTxt(doc, C.light);
    doc.text(evLines, COL1_X + 7, y1 + 1.5);
    y1 += evH + 2;
  });

  // ── RIGHT COLUMN ────────────────────────────────────────────────────────────

  // D) COUNTERFACTUAL ANALYSIS
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  setTxt(doc, C.amber);
  doc.text("COUNTERFACTUAL ANALYSIS", COL2_X, y2);
  setDraw(doc, C.amber);
  doc.setLineWidth(0.3);
  doc.line(COL2_X, y2 + 1, COL2_X + COL_W, y2 + 1);
  y2 += 5;

  const cf       = explainData.counterfactual_analysis ?? {};
  const question = cf.question ?? "Under what conditions would this case NOT have been flagged?";
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7.5);
  setTxt(doc, C.muted);
  const qLines = doc.splitTextToSize(question, COL_W);
  doc.text(qLines, COL2_X, y2);
  y2 += qLines.length * 4.4 + 3;

  const scenarios = cf.scenarios ?? [];
  scenarios.forEach((s: string) => {
    const sLines = doc.splitTextToSize(s, COL_W - 9);
    const sH     = sLines.length * 4.4 + 6;
    setFill(doc, [26, 22, 8]);
    setDraw(doc, [85, 72, 20]);
    doc.setLineWidth(0.25);
    doc.roundedRect(COL2_X, y2, COL_W, sH, 1.5, 1.5, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    setTxt(doc, C.amber);
    doc.text("→", COL2_X + 2.5, y2 + sH / 2 + 1.5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.8);
    setTxt(doc, [210, 195, 130]);
    doc.text(sLines, COL2_X + 8, y2 + 4.5);
    y2 += sH + 2.5;
  });

  y2 += 4;

  // E) POLICY THRESHOLDS
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  setTxt(doc, C.emerald);
  doc.text("POLICY THRESHOLDS", COL2_X, y2);
  setDraw(doc, C.emerald);
  doc.setLineWidth(0.3);
  doc.line(COL2_X, y2 + 1, COL2_X + COL_W, y2 + 1);
  y2 += 5;

  const pc = explainData.policy_context ?? {};
  const thresholds: Array<{ label: string; value: string }> = [];
  if (pc.invoice_approval_threshold != null)
    thresholds.push({ label: "Invoice Approval Threshold", value: `₹${Number(pc.invoice_approval_threshold).toLocaleString("en-IN")}` });
  if (pc.large_payment_threshold != null)
    thresholds.push({ label: "Large Payment Threshold", value: `₹${Number(pc.large_payment_threshold).toLocaleString("en-IN")}` });
  if (pc.rapid_payment_max_days != null)
    thresholds.push({ label: "Rapid Payment Window", value: `${pc.rapid_payment_max_days} days` });
  if (pc.invoice_splitting_window_days != null)
    thresholds.push({ label: "Invoice Splitting Window", value: `${pc.invoice_splitting_window_days} days` });
  if (pc.invoice_splitting_min_count != null)
    thresholds.push({ label: "Min Invoices for Split", value: String(pc.invoice_splitting_min_count) });
  if (pc.dormancy_threshold_days != null)
    thresholds.push({ label: "Vendor Dormancy Threshold", value: `${pc.dormancy_threshold_days} days` });
  if (pc.senior_approvers?.length > 0)
    thresholds.push({ label: "Senior Approvers", value: pc.senior_approvers.join(", ") });

  thresholds.forEach((t, i) => {
    const rowY = y2 + i * 7.5;
    setFill(doc, i % 2 === 0 ? C.card : [14, 16, 24]);
    doc.rect(COL2_X, rowY, COL_W, 7, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setTxt(doc, C.muted);
    doc.text(t.label, COL2_X + 3, rowY + 4.8);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    setTxt(doc, C.emerald);
    doc.text(t.value, COL2_X + COL_W - 3, rowY + 4.8, { align: "right" });
  });
  y2 += thresholds.length * 7.5 + 4;

  // ── GRAPH TRACEABILITY (full width) ─────────────────────────────────────────
  const yBottom = Math.max(y1, y2) + 6;
  setDraw(doc, C.border);
  doc.setLineWidth(0.3);
  doc.line(10, yBottom, W - 10, yBottom);

  const tracY = yBottom + 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  setTxt(doc, C.purple);
  doc.text("GRAPH TRACEABILITY", 10, tracY);
  setDraw(doc, C.purple);
  doc.setLineWidth(0.3);
  doc.line(10, tracY + 1, W - 10, tracY + 1);

  const traceability = explainData.traceability ?? [];
  if (traceability.length > 0) {
    const stepW = Math.min((W - 22) / traceability.length - 3, 34);
    traceability.forEach((step: any, i: number) => {
      const sx = 10 + i * (stepW + 5);
      const sy = tracY + 5;
      setFill(doc, [20, 16, 36]);
      setDraw(doc, C.purple);
      doc.setLineWidth(0.3);
      doc.roundedRect(sx, sy, stepW, 18, 1.5, 1.5, "FD");

      // Step circle
      setFill(doc, C.purple);
      doc.circle(sx + 5, sy + 5, 3, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6);
      setTxt(doc, C.white);
      doc.text(String(step.step), sx + 5, sy + 6.5, { align: "center" });

      // Node type
      doc.setFont("helvetica", "bold");
      doc.setFontSize(6.5);
      setTxt(doc, C.purple);
      const typeLbl  = (step.type ?? "unknown").replace(/_/g, " ").toUpperCase();
      const typeLines = doc.splitTextToSize(typeLbl, stepW - 4);
      doc.text(typeLines, sx + stepW / 2, sy + 9, { align: "center" });

      // Node ID
      doc.setFont("courier", "normal");
      doc.setFontSize(5.5);
      setTxt(doc, C.muted);
      doc.text(String(step.node ?? "").substring(0, 14), sx + stepW / 2, sy + 15, { align: "center" });

      // Arrow connector
      if (i < traceability.length - 1) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        setTxt(doc, C.border);
        doc.text("›", sx + stepW + 1, sy + 11);
      }
    });
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    setTxt(doc, C.muted);
    doc.text("Graph path not available — run the audit pipeline to populate traceability.", 10, tracY + 10);
  }

  // ── FOOTER ──────────────────────────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addPageFooter(doc);
  }

  // ── SAVE ────────────────────────────────────────────────────────────────────
  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`FinSentry_Case_${explainData.case_id ?? "Report"}_${dateStr}.pdf`);
}

// ─── Main export function ────────────────────────────────────────────────────
export function generateAuditPDF(investigationData: any, complianceData?: any) {
  const doc = new jsPDF({ unit: "mm", format: "a4", compress: true });
  const W = doc.internal.pageSize.getWidth();
  const findings: any[] = investigationData?.findings ?? [];

  // ── COVER PAGE ────────────────────────────────────────────────────────────
  addCoverPage(doc, investigationData);

  // ── PAGE 2: EXECUTIVE SUMMARY ─────────────────────────────────────────────
  doc.addPage();
  setFill(doc, C.bg);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), doc.internal.pageSize.getHeight(), "F");

  let y = 22;
  y = sectionHeading(doc, y, "01 — EXECUTIVE NARRATIVE");

  const narrative = investigationData?.narrative ?? "";
  if (narrative) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    setTxt(doc, C.light);
    const lines = doc.splitTextToSize(narrative, W - 30);
    doc.text(lines, 15, y);
    y += lines.length * 5.5 + 8;
  } else {
    setTxt(doc, C.muted);
    doc.setFontSize(9);
    doc.text("No narrative generated. Run the audit pipeline to generate an AI summary.", 15, y);
    y += 12;
  }

  // ── Compliance summary (if available) ─────────────────────────────────────
  if (complianceData) {
    y += 4;
    y = sectionHeading(doc, y, "02 — COMPLIANCE SNAPSHOT");

    const cp = complianceData;
    const snapStats = [
      { label: "Compliance Score",     value: `${cp.compliance_score}%` },
      { label: "Controls Passed",      value: `${cp.controls_passed} / ${cp.controls_total}` },
      { label: "Flagged Transactions", value: `${cp.flagged_transactions} / ${cp.total_transactions}` },
      { label: "Active Findings",      value: String(cp.total_findings) },
    ];

    const cellW = (W - 30) / 4;
    snapStats.forEach((s, i) => {
      const x = 15 + i * cellW;
      setFill(doc, C.card);
      doc.rect(x, y, cellW - 3, 20, "F");
      setDraw(doc, C.border);
      doc.setLineWidth(0.3);
      doc.rect(x, y, cellW - 3, 20, "S");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      const scoreColor = i === 0
        ? (cp.compliance_score >= 80 ? C.emerald : cp.compliance_score >= 60 ? C.amber : C.crimson)
        : C.primary;
      setTxt(doc, scoreColor);
      doc.text(s.value, x + (cellW - 3) / 2, y + 10, { align: "center" });
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6.5);
      setTxt(doc, C.muted);
      doc.text(s.label.toUpperCase(), x + (cellW - 3) / 2, y + 17, { align: "center" });
    });
    y += 28;

    // Control categories table
    if (cp.categories?.length > 0) {
      autoTable(doc, {
        startY: y,
        margin: { left: 15, right: 15 },
        head: [["Control Category", "Rule", "Status", "Violations"]],
        body: cp.categories.map((c: any) => [
          c.name,
          c.control,
          c.status,
          String(c.violations),
        ]),
        styles: {
          font: "helvetica",
          fontSize: 8,
          cellPadding: 3,
          fillColor: C.card,
          textColor: C.light,
          lineColor: C.border,
          lineWidth: 0.2,
        },
        headStyles: {
          fillColor: [20, 22, 35],
          textColor: C.primary,
          fontStyle: "bold",
          fontSize: 8,
        },
        columnStyles: {
          0: { cellWidth: 45 },
          1: { cellWidth: "auto" },
          2: { cellWidth: 18, halign: "center" },
          3: { cellWidth: 18, halign: "center" },
        },
        didParseCell(data) {
          if (data.column.index === 2 && data.section === "body") {
            const val = String(data.cell.raw ?? "");
            data.cell.styles.textColor = val === "PASS" ? C.emerald : C.crimson;
            data.cell.styles.fontStyle = "bold";
          }
          if (data.column.index === 3 && data.section === "body") {
            const val = Number(data.cell.raw ?? 0);
            if (val > 0) data.cell.styles.textColor = C.crimson;
          }
        },
        theme: "grid",
      });
      y = (doc as any).lastAutoTable.finalY + 10;
    }
  }

  // ── PAGE 3+: RISK FINDINGS ────────────────────────────────────────────────
  if (findings.length > 0) {
    doc.addPage();
    setFill(doc, C.bg);
    doc.rect(0, 0, doc.internal.pageSize.getWidth(), doc.internal.pageSize.getHeight(), "F");
    y = 22;
    y = sectionHeading(doc, y, `03 — RISK FINDINGS SUMMARY  (${findings.length} total)`);

    // Summary table
    autoTable(doc, {
      startY: y,
      margin: { left: 15, right: 15 },
      head: [["#", "Risk Type", "Vendor", "Label", "Risk Score", "Policy Violation"]],
      body: findings.map((f: any, i: number) => [
        String(i + 1),
        (f.risk_type ?? "").replace(/_/g, " ").toUpperCase(),
        f.vendor ?? "—",
        f.risk_label ?? "—",
        f.risk_score != null ? `${Math.round(f.risk_score * 100)}%` : "—",
        (f.policy_violation ?? "—").substring(0, 60) + ((f.policy_violation?.length ?? 0) > 60 ? "…" : ""),
      ]),
      styles: {
        font: "helvetica",
        fontSize: 7.5,
        cellPadding: 3,
        fillColor: C.card,
        textColor: C.light,
        lineColor: C.border,
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: [20, 22, 35],
        textColor: C.primary,
        fontStyle: "bold",
        fontSize: 8,
      },
      columnStyles: {
        0: { cellWidth: 8, halign: "center" },
        1: { cellWidth: 42 },
        2: { cellWidth: 30 },
        3: { cellWidth: 18, halign: "center" },
        4: { cellWidth: 18, halign: "center" },
        5: { cellWidth: "auto" },
      },
      didParseCell(data) {
        if (data.column.index === 3 && data.section === "body") {
          const val = String(data.cell.raw ?? "");
          data.cell.styles.textColor = labelColor(val);
          data.cell.styles.fontStyle = "bold";
        }
        if (data.column.index === 4 && data.section === "body") {
          const pct = parseInt(String(data.cell.raw ?? "0"), 10);
          data.cell.styles.textColor = pct >= 80 ? C.crimson : pct >= 65 ? C.amber : C.primary;
        }
      },
      theme: "grid",
    });

    // ── DETAIL PAGES: one per finding ─────────────────────────────────────
    findings.forEach((f: any, idx: number) => {
      doc.addPage();
      setFill(doc, C.bg);
      doc.rect(0, 0, doc.internal.pageSize.getWidth(), doc.internal.pageSize.getHeight(), "F");

      y = 22;
      const riskColor = RISK_TYPE_COLORS[f.risk_type] ?? C.muted;
      y = sectionHeading(doc, y, `FINDING ${idx + 1} OF ${findings.length} — ${(f.risk_type ?? "").replace(/_/g, " ").toUpperCase()}`);

      // Finding header panel
      setFill(doc, C.card);
      doc.rect(15, y, W - 30, 26, "F");
      setDraw(doc, riskColor);
      doc.setLineWidth(0.5);
      doc.rect(15, y, W - 30, 26, "S");
      setFill(doc, riskColor);
      doc.rect(15, y, 2.5, 26, "F");

      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      setTxt(doc, C.white);
      doc.text(f.vendor ?? "Unknown Vendor", 22, y + 9);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      setTxt(doc, C.muted);
      const lbl = f.risk_label ?? "—";
      const score = f.risk_score != null ? `${Math.round(f.risk_score * 100)}%` : "—";
      doc.text(`Label: `, 22, y + 17);
      setTxt(doc, labelColor(lbl));
      doc.setFont("helvetica", "bold");
      doc.text(lbl, 33, y + 17);
      doc.setFont("helvetica", "normal");
      setTxt(doc, C.muted);
      doc.text(`   ·   Risk Score: ${score}   ·   Status: ${(f.status ?? "open").replace(/_/g, " ")}`, 33 + doc.getTextWidth(lbl), y + 17);
      y += 32;

      // Evidence
      if (f.evidence?.length > 0) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        setTxt(doc, C.primary);
        doc.text("EVIDENCE", 15, y);
        y += 5;
        f.evidence.forEach((ev: string) => {
          doc.setFont("helvetica", "normal");
          doc.setFontSize(8.5);
          setTxt(doc, C.light);
          const lines = doc.splitTextToSize(`• ${ev}`, W - 36);
          doc.text(lines, 18, y);
          y += lines.length * 5 + 1.5;
        });
        y += 3;
      }

      // Policy Violation
      if (f.policy_violation) {
        setFill(doc, [40, 10, 10]);
        const pvLines = doc.splitTextToSize(f.policy_violation, W - 46);
        const pvH = pvLines.length * 5 + 8;
        doc.rect(15, y, W - 30, pvH, "F");
        setDraw(doc, C.crimson);
        doc.setLineWidth(0.4);
        doc.rect(15, y, W - 30, pvH, "S");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        setTxt(doc, C.crimson);
        doc.text("POLICY VIOLATION", 20, y + 5);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        setTxt(doc, C.light);
        doc.text(pvLines, 20, y + 11);
        y += pvH + 6;
      }

      // Financial Effect
      if (f.effect) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        setTxt(doc, C.amber);
        doc.text("FINANCIAL EFFECT", 15, y);
        y += 5;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        setTxt(doc, C.light);
        const efLines = doc.splitTextToSize(f.effect, W - 36);
        doc.text(efLines, 18, y);
        y += efLines.length * 5 + 5;
      }

      // Recommendation
      if (f.recommendation) {
        setFill(doc, [10, 30, 18]);
        const recLines = doc.splitTextToSize(f.recommendation, W - 46);
        const recH = recLines.length * 5 + 8;
        doc.rect(15, y, W - 30, recH, "F");
        setDraw(doc, C.emerald);
        doc.setLineWidth(0.4);
        doc.rect(15, y, W - 30, recH, "S");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        setTxt(doc, C.emerald);
        doc.text("RECOMMENDATION", 20, y + 5);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8.5);
        setTxt(doc, C.light);
        doc.text(recLines, 20, y + 11);
        y += recH + 6;
      }

      // Graph path
      if (f.graph_path?.length > 0) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7.5);
        setTxt(doc, C.primary);
        doc.text("DETECTION PATHWAY (GRAPH TRAVERSAL)", 15, y);
        y += 5;
        const pathText = f.graph_path.join("  →  ");
        doc.setFont("courier", "normal");
        doc.setFontSize(7.5);
        setTxt(doc, [0, 188, 212]);
        const pathLines = doc.splitTextToSize(pathText, W - 36);
        doc.text(pathLines, 18, y);
        y += pathLines.length * 5;
      }
    });
  }

  // ── Apply headers/footers to all pages ────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    if (p > 1) {  // Cover has its own header treatment
      addPageHeader(doc, p, totalPages);
    }
    addPageFooter(doc);
  }

  // ── Save ──────────────────────────────────────────────────────────────────
  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`FinSentry_Audit_Report_${dateStr}.pdf`);
}

// ─── Auditor Narrative Report ─────────────────────────────────────────────────
export function generateAuditorReport(opts: {
  caseItem: any;
  title: string;
  executiveSummary: string;
  detailedFindings: string;
  riskAssessment: string;
  recommendedActions: string;
  auditorName: string;
  reportDate: string;
}) {
  const { caseItem, title, executiveSummary, detailedFindings, riskAssessment, recommendedActions, auditorName, reportDate } = opts;
  const doc = new jsPDF({ unit: "mm", format: "a4", compress: true });
  const W = 210;
  const H = 297;
  const M = 15; // margin

  const riskColor = RISK_LABEL_COLORS[caseItem.risk_label] ?? C.muted;
  const amber = C.amber;

  // ── helper ──────────────────────────────────────────────────────────────────
  function pageHeader() {
    setFill(doc, C.card);
    doc.rect(0, 0, W, 12, "F");
    setFill(doc, amber);
    doc.rect(0, 12, W, 0.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    setTxt(doc, amber);
    doc.text("FinSentry  ·  AUDITOR REPORT", M, 8);
    doc.setFont("helvetica", "normal");
    setTxt(doc, C.muted);
    doc.text(`${caseItem.case_id ?? ""} · ${auditorName || "Auditor"}`, W - M, 8, { align: "right" });
  }

  function addSection(label: string, content: string, color: [number, number, number], startY: number): number {
    if (!content.trim()) return startY + 2;
    if (startY > H - 50) {
      doc.addPage();
      setFill(doc, C.bg);
      doc.rect(0, 0, W, H, "F");
      pageHeader();
      startY = 22;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setTxt(doc, color);
    doc.text(label, M, startY);
    setDraw(doc, color);
    doc.setLineWidth(0.4);
    doc.line(M, startY + 1.5, W - M, startY + 1.5);
    startY += 7;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    setTxt(doc, C.light);
    const lines = doc.splitTextToSize(content, W - M * 2);
    const blockH = lines.length * 5.4;
    if (startY + blockH > H - 20) {
      doc.addPage();
      setFill(doc, C.bg);
      doc.rect(0, 0, W, H, "F");
      pageHeader();
      startY = 22;
    }
    doc.text(lines, M, startY);
    return startY + blockH + 10;
  }

  // ── COVER PAGE ───────────────────────────────────────────────────────────────
  setFill(doc, C.bg);
  doc.rect(0, 0, W, H, "F");

  // Amber accent top bar
  setFill(doc, amber);
  doc.rect(0, 0, W, 2.5, "F");

  // Hero zone
  setFill(doc, C.card);
  doc.rect(0, 20, W, 72, "F");
  setFill(doc, amber);
  doc.rect(0, 92, W, 0.5, "F");

  // Report type badge
  setFill(doc, amber);
  doc.roundedRect(M, 30, 58, 8.5, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  setTxt(doc, [10, 8, 0]);
  doc.text("AUDITOR INVESTIGATION REPORT", M + 29, 36, { align: "center" });

  // FinSentry brand
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setTxt(doc, C.muted);
  doc.text("FinSentry", W - M, 35, { align: "right" });

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  setTxt(doc, C.white);
  const titleLines = doc.splitTextToSize(title || `Audit Report — ${caseItem.case_id ?? ""}`, W - M * 2 - 4);
  doc.text(titleLines, M, 55);

  // ── METADATA TABLE ─────────────────────────────────────────────────────────
  const metaY = 105;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  setTxt(doc, amber);
  doc.text("CASE METADATA", M, metaY);
  setDraw(doc, amber);
  doc.setLineWidth(0.4);
  doc.line(M, metaY + 1.5, W - M, metaY + 1.5);

  const metaRows = [
    ["Case ID",         caseItem.case_id ?? "—"],
    ["Vendor",          caseItem.vendor ?? "—"],
    ["Risk Type",       (caseItem.risk_type ?? "").replace(/_/g, " ").toUpperCase()],
    ["Risk Label",      caseItem.risk_label ?? "—"],
    ["Risk Score",      caseItem.risk_score != null ? `${Math.round(caseItem.risk_score * 100)}%` : "—"],
    ["Governance Area", caseItem.governance_area ?? "—"],
    ["Auditor",         auditorName || "—"],
    ["Report Date",     reportDate || new Date().toLocaleDateString("en-GB")],
  ];

  let mY = metaY + 6;
  metaRows.forEach(([lbl, val], i) => {
    setFill(doc, i % 2 === 0 ? [16, 18, 26] : C.card);
    doc.rect(M, mY - 2, W - M * 2, 7, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    setTxt(doc, C.muted);
    doc.text(lbl, M + 2, mY + 2.8);
    doc.setFont("helvetica", "bold");
    setTxt(doc, C.light);
    doc.text(val, M + 65, mY + 2.8);
    mY += 7;
  });

  // Risk classification footer
  setFill(doc, riskColor);
  doc.rect(0, H - 18, W, 0.8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  setTxt(doc, riskColor);
  doc.text(`RISK CLASSIFICATION: ${caseItem.risk_label ?? "UNKNOWN"}`, M, H - 10);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  setTxt(doc, C.muted);
  doc.text("CONFIDENTIAL — FinSentry Compliance Platform · Deloitte Hackplosion 2026", W - M, H - 10, { align: "right" });

  // ── NARRATIVE PAGES ─────────────────────────────────────────────────────────
  doc.addPage();
  setFill(doc, C.bg);
  doc.rect(0, 0, W, H, "F");
  pageHeader();
  let y = 22;

  y = addSection("01 — EXECUTIVE SUMMARY", executiveSummary || "(No content provided)", C.primary, y);
  y = addSection("02 — DETAILED FINDINGS", detailedFindings || "(No content provided)", C.crimson, y);
  y = addSection("03 — RISK ASSESSMENT", riskAssessment || "(No content provided)", amber, y);
  y = addSection("04 — RECOMMENDED ACTIONS", recommendedActions || "(No content provided)", C.emerald, y);

  // ── EVIDENCE PAGE ────────────────────────────────────────────────────────────
  const evidence: string[] = caseItem.evidence ?? [];
  if (evidence.length > 0) {
    if (y > H - 60) {
      doc.addPage();
      setFill(doc, C.bg);
      doc.rect(0, 0, W, H, "F");
      pageHeader();
      y = 22;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setTxt(doc, C.primary);
    doc.text("05 — SYSTEM-DETECTED EVIDENCE", M, y);
    setDraw(doc, C.primary);
    doc.setLineWidth(0.4);
    doc.line(M, y + 1.5, W - M, y + 1.5);
    y += 8;

    evidence.forEach(ev => {
      const evLines = doc.splitTextToSize(ev, W - M * 2 - 8);
      const evH = evLines.length * 4.8 + 5;
      if (y + evH > H - 20) {
        doc.addPage();
        setFill(doc, C.bg);
        doc.rect(0, 0, W, H, "F");
        pageHeader();
        y = 22;
      }
      setFill(doc, C.card);
      doc.rect(M, y - 1.5, W - M * 2, evH, "F");
      setFill(doc, C.primary);
      doc.circle(M + 3, y + 1.5, 1.2, "F");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      setTxt(doc, C.light);
      doc.text(evLines, M + 8, y + 1.5);
      y += evH + 2.5;
    });
  }

  // ── DETECTION PATHWAY ────────────────────────────────────────────────────────
  if ((caseItem.graph_path ?? []).length > 0) {
    y += 6;
    if (y + 30 > H - 20) {
      doc.addPage();
      setFill(doc, C.bg);
      doc.rect(0, 0, W, H, "F");
      pageHeader();
      y = 22;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    setTxt(doc, C.purple);
    doc.text("06 — DETECTION PATHWAY", M, y);
    setDraw(doc, C.purple);
    doc.setLineWidth(0.4);
    doc.line(M, y + 1.5, W - M, y + 1.5);
    y += 8;

    const path: string[] = caseItem.graph_path;
    const stepW = Math.min((W - M * 2) / path.length - 3, 36);
    path.forEach((node, i) => {
      const sx = M + i * (stepW + 4);
      setFill(doc, [20, 16, 36]);
      setDraw(doc, C.purple);
      doc.setLineWidth(0.3);
      doc.roundedRect(sx, y, stepW, 14, 1.5, 1.5, "FD");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(5.5);
      setTxt(doc, C.purple);
      doc.text(String(i + 1), sx + 5, y + 5.5, { align: "center" });
      doc.setFont("courier", "normal");
      doc.setFontSize(5);
      setTxt(doc, C.muted);
      doc.text(node.substring(0, 16), sx + stepW / 2, y + 11, { align: "center" });
      if (i < path.length - 1) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        setTxt(doc, C.border);
        doc.text("›", sx + stepW + 0.5, y + 9);
      }
    });
    y += 22;
  }

  // ── SIGNATURE BLOCK ──────────────────────────────────────────────────────────
  y += 10;
  if (y + 20 > H - 20) {
    doc.addPage();
    setFill(doc, C.bg);
    doc.rect(0, 0, W, H, "F");
    pageHeader();
    y = 22;
  }
  setDraw(doc, C.border);
  doc.setLineWidth(0.3);
  doc.line(M, y, M + 65, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setTxt(doc, C.muted);
  doc.text(auditorName || "Auditor Signature", M, y + 5.5);
  doc.text(`Date: ${reportDate || new Date().toLocaleDateString("en-GB")}`, M, y + 11);

  addPageFooter(doc);

  // ── SAVE ─────────────────────────────────────────────────────────────────────
  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`FinSentry_Auditor_Report_${caseItem.case_id ?? "Case"}_${dateStr}.pdf`);
}
