// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title AuditEventRegistry
/// @notice Anchors audit/supply-chain event proofs on-chain.
/// @dev Designed for backend-relayer submissions (no end-user wallet dependency).
contract AuditEventRegistry {
    struct AnchoredEvent {
        bytes32 eventHash;
        string eventType;
        string entityId;
        string ipfsCid;
        uint256 occurredAt;
        uint256 anchoredAt;
        address submitter;
        bool exists;
    }

    address public owner;
    mapping(address => bool) public isRelayer;
    mapping(bytes32 => AnchoredEvent) private anchors;

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    event RelayerUpdated(address indexed relayer, bool enabled);
    event EventAnchored(
        bytes32 indexed anchorId,
        bytes32 indexed eventHash,
        string eventType,
        string entityId,
        string ipfsCid,
        uint256 occurredAt,
        uint256 anchoredAt,
        address indexed submitter
    );

    error NotOwner();
    error NotAuthorized();
    error ZeroAddress();
    error AnchorAlreadyExists(bytes32 anchorId);
    error AnchorNotFound(bytes32 anchorId);
    error EmptyValue(string field);

    modifier onlyOwner() {
        if (msg.sender != owner) {
            revert NotOwner();
        }
        _;
    }

    modifier onlyWriter() {
        if (!(msg.sender == owner || isRelayer[msg.sender])) {
            revert NotAuthorized();
        }
        _;
    }

    constructor(address initialOwner) {
        if (initialOwner == address(0)) {
            revert ZeroAddress();
        }
        owner = initialOwner;
        emit OwnershipTransferred(address(0), initialOwner);
    }

    function transferOwnership(address newOwner) external onlyOwner {
        if (newOwner == address(0)) {
            revert ZeroAddress();
        }
        address prev = owner;
        owner = newOwner;
        emit OwnershipTransferred(prev, newOwner);
    }

    function setRelayer(address relayer, bool enabled) external onlyOwner {
        if (relayer == address(0)) {
            revert ZeroAddress();
        }
        isRelayer[relayer] = enabled;
        emit RelayerUpdated(relayer, enabled);
    }

    /// @notice Anchor a single event proof.
    /// @param anchorId Stable identifier generated by backend (for example, hash(trace_id + stage)).
    /// @param eventHash SHA-256 hash of canonical event payload.
    /// @param eventType Category such as "risk.detected", "case.updated", "policy.updated".
    /// @param entityId Business identifier (case id, invoice id, transaction id, etc).
    /// @param ipfsCid CID for detailed evidence JSON (optional, can be empty).
    /// @param occurredAt UTC unix timestamp when event happened in business system.
    function anchorEvent(
        bytes32 anchorId,
        bytes32 eventHash,
        string calldata eventType,
        string calldata entityId,
        string calldata ipfsCid,
        uint256 occurredAt
    ) external onlyWriter {
        if (anchors[anchorId].exists) {
            revert AnchorAlreadyExists(anchorId);
        }
        if (eventHash == bytes32(0)) {
            revert EmptyValue("eventHash");
        }
        if (bytes(eventType).length == 0) {
            revert EmptyValue("eventType");
        }
        if (bytes(entityId).length == 0) {
            revert EmptyValue("entityId");
        }
        if (occurredAt == 0) {
            revert EmptyValue("occurredAt");
        }

        uint256 anchoredAt = block.timestamp;
        anchors[anchorId] = AnchoredEvent({
            eventHash: eventHash,
            eventType: eventType,
            entityId: entityId,
            ipfsCid: ipfsCid,
            occurredAt: occurredAt,
            anchoredAt: anchoredAt,
            submitter: msg.sender,
            exists: true
        });

        emit EventAnchored(
            anchorId,
            eventHash,
            eventType,
            entityId,
            ipfsCid,
            occurredAt,
            anchoredAt,
            msg.sender
        );
    }

    function getAnchor(bytes32 anchorId) external view returns (AnchoredEvent memory) {
        AnchoredEvent memory a = anchors[anchorId];
        if (!a.exists) {
            revert AnchorNotFound(anchorId);
        }
        return a;
    }

    function anchorExists(bytes32 anchorId) external view returns (bool) {
        return anchors[anchorId].exists;
    }
}
